// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod config;
mod commands;
mod state;
mod db_pool;
mod concurrency_tests;

use config::AppConfig;
use commands::*;
use state::DbConnection;
use std::sync::Mutex;
use tauri::Manager;

fn main() {
    AppConfig::init();

    tauri::Builder::default()
        .manage(DbConnection {
            pool: Mutex::new(None),
            dek: Mutex::new(None),
            p2p_sync: Mutex::new(None),
        })
        .on_window_event(|event| {
            if let tauri::WindowEvent::CloseRequested { .. } = event.event() {
                if let Some(app) = event.window().app_handle().try_state::<DbConnection>() {
                    if let Ok(mut dek_guard) = app.dek.lock() {
                        *dek_guard = None;
                    }
                }
            }
        })
        .invoke_handler(tauri::generate_handler![
            create_vault_cmd,
            unlock_vault_cmd,
            get_project_cmd,
            get_projects_in_space_cmd,
            get_project_milestones_cmd,
            get_project_risks_cmd,
            get_project_updates_cmd,
            create_project_risk_cmd,
            delete_project_cmd,
            update_project_cmd,
            create_saved_search_cmd,
            get_saved_search_cmd,
            get_saved_searches_cmd,
            update_saved_search_cmd,
            delete_saved_search_cmd,
            execute_saved_search_cmd,
            generate_weekly_review_cmd,
            get_space_modes_cmd,
            enable_mode_cmd,
            disable_mode_cmd,
            create_note_cmd,
            get_note_cmd,
            update_note_content_cmd,
            trash_note_cmd,
            create_task_cmd,
            get_task_cmd,
            update_task_cmd,
            delete_task_cmd,
            get_tasks_by_project_cmd,
            get_due_cards_cmd,
            review_card_cmd,
            get_all_notes_in_space_cmd,
            get_all_tasks_in_space_cmd,
            import_from_obsidian_cmd,
            import_from_notion_cmd,
            create_form_template_cmd,
            get_form_template_cmd,
            get_form_templates_for_space_cmd,
            update_form_template_cmd,
            delete_form_template_cmd,
            get_analytics_data_cmd,
            search_notes_cmd,
            get_or_create_daily_note_cmd,
            get_all_spaces_cmd,
            get_all_tags_in_space_cmd,
            get_upcoming_tasks_cmd,
            get_recent_notes_cmd,
            start_time_entry_cmd,
            stop_time_entry_cmd,
            get_task_time_entries_cmd,
            get_project_time_entries_cmd,
            get_running_entries_cmd,
            get_recent_time_entries_cmd,
            get_task_time_stats_cmd,
            get_project_time_stats_cmd,
            delete_time_entry_cmd,
            create_manual_time_entry_cmd,
            queue_ocr_cmd,
            get_ocr_status_cmd,
            search_ocr_text_cmd,
            process_ocr_job_cmd,
            generate_insights_cmd,
            get_active_insights_cmd,
            dismiss_insight_cmd,
            record_feedback_cmd,
            add_caldav_account_cmd,
            get_caldav_accounts_cmd,
            get_caldav_account_cmd,
            update_caldav_account_cmd,
            delete_caldav_account_cmd,
            sync_caldav_account_cmd,
            get_caldav_sync_history_cmd,
            get_caldav_conflicts_cmd,
            resolve_caldav_conflict_cmd,
            init_sync_tables_cmd,
            get_devices_cmd,
            register_device_cmd,
            get_sync_history_for_space_cmd,
            get_sync_conflicts_cmd,
            resolve_sync_conflict_cmd,
            record_sync_cmd,
            start_p2p_sync_cmd,
            create_health_metric_cmd,
            get_health_metrics_cmd,
            create_transaction_cmd,
            get_transactions_cmd,
            create_recipe_cmd,
            get_recipes_cmd,
            create_trip_cmd,
            get_trips_cmd,
            build_current_graph_cmd,
            get_graph_evolution_cmd,
            detect_major_notes_cmd,
            shutdown_clear_keys_cmd,
            init_rbac_tables_cmd,
            get_space_users_cmd,
            check_permission_cmd,
            invite_user_cmd,
            update_user_role_cmd,
            grant_permission_cmd,
            revoke_permission_cmd,
            suspend_user_cmd,
            activate_user_cmd,
            get_roles_cmd,
            add_user_to_space_cmd,
            remove_user_from_space_cmd,
            add_social_account_cmd,
            get_social_accounts_cmd,
            get_social_account_cmd,
            update_social_account_cmd,
            delete_social_account_cmd,
            store_social_posts_cmd,
            get_unified_timeline_cmd,
            create_category_cmd,
            get_categories_cmd,
            assign_category_cmd,
            delete_category_cmd,
            get_timeline_stats_cmd,
            get_analytics_overview_cmd,
            search_social_posts_cmd,
            auto_categorize_posts_cmd,
            create_webview_session_cmd,
            get_webview_session_cmd,
            save_session_cookies_cmd,
            get_all_sync_tasks_cmd,
            get_sync_stats_cmd,
            create_backup_cmd,
            restore_backup_cmd,
            list_backups_cmd,
            delete_backup_cmd,
            get_backup_details_cmd,
            create_user_cmd,
            authenticate_user_cmd,
            validate_session_cmd,
            logout_user_cmd,
            get_user_by_id_cmd,
            change_password_cmd,
            get_current_user_cmd,
            discover_devices_cmd,
            initiate_pairing_cmd,
            exchange_keys_cmd,
            get_sync_progress_cmd,
            cancel_sync_cmd,
            get_or_create_user_id_cmd,
            start_sync_server_cmd,
            get_dashboard_stats_cmd,
            create_goal_cmd,
            get_goals_cmd,
            update_goal_progress_cmd,
            delete_goal_cmd,
            create_habit_cmd,
            get_habits_cmd,
            complete_habit_cmd,
            delete_habit_cmd
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
